spring.datasource.url=jdbc:postgresql://localhost:5432/jbase
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.default-model-expand-depth=3
springdoc.swagger-ui.try-it-out-enabled=true
